spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tasks?currentSchema=tasks
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: never
      continue-on-error: false
      data-locations: classpath:demo_data.sql
security:
  jwt:
    secret: cWF6d3N4ZWRjcmZ2dGdieWhudWptaWssb2wucDsvWydd
    access: 3600000
    refresh: 2592000000