spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tasks?currentSchema=tasks
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: never
      continue-on-error: false
      data-locations: classpath:demo_data.sql
  liquibase:
    enabled: true
    change-log: classpath:liquibase/db.changelog.yaml
    default-schema: tasks
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
security:
  jwt:
    secret: cWF6d3N4ZWRjcmZ2dGdieWhudWptaWssb2wucDsvWydd
    access: 3600000
    refresh: 2592000000
springdoc:
  override-with-generic-response: false