name: gradle-build
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  checkstyle:
    runs-on: ubuntu-20.4
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
      - uses: actions/cache@v3
        with:
          path: ~/.gradle/caches/modules-2
          key: gradle-${{ hashFiles('**/build.gradle*') }}
          restore-keys: |
            gradle-
      - run: gradle clean build